services:
  caddy:
    image: caddy:2-alpine
    container_name: packingsite_caddy
    network_mode: host
    volumes:
      - ./Caddyfile.dev:/etc/caddy/Caddyfile:ro
      - ./frontend:/srv/frontend:ro
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - SITE_URL=${SITE_URL:-https://localhost}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-https://localhost}
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build: .
    container_name: packingsite_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/code/backend
      - ./stores:/code/stores
      - ./floorplans:/code/floorplans
      - ./db:/db
      - ./tools:/code/tools
    env_file:
      - .env
    environment:
      # Override specific values for development
      - SQLITE_DB_PATH=/db/packingwebsite.db
      - SMTP_HOST=${SMTP_HOST:-mailhog}
      - SMTP_PORT=${SMTP_PORT:-1025}
    depends_on:
      - mailhog
    restart: unless-stopped

  mailhog:
    image: mailhog/mailhog:latest
    container_name: packingsite_mailhog
    ports:
      - "8026:8025" # Web UI (8026 on host, 8025 in container)
      - "1026:1025" # SMTP Server (1026 on host, 1025 in container)
    restart: unless-stopped

  test:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./package.json:/app/package.json:ro
      - ./vitest.config.js:/app/vitest.config.js:ro
      - ./frontend/js/lib:/app/lib:ro
      - ./frontend/js/components:/app/components:ro
      - ./frontend/tests:/app/tests:ro
      - node_modules:/app/node_modules
    command: sh -c "npm install && npm test"
    profiles: ["test"]

volumes:
  node_modules:
  caddy_data:
  caddy_config:
